# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PixivAgent.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(386, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMinimumSize(QtCore.QSize(386, 99))
        main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_login = QtWidgets.QWidget(main)
        self.widget_login.setObjectName("widget_login")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_login)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget_login)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.email = QtWidgets.QLineEdit(self.widget_login)
        self.email.setObjectName("email")
        self.horizontalLayout_5.addWidget(self.email)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_login)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.password = QtWidgets.QLineEdit(self.widget_login)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout_4.addWidget(self.password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.btn_login = QtWidgets.QPushButton(self.widget_login)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_2.addWidget(self.btn_login)
        self.verticalLayout.addWidget(self.widget_login)
        self.widget_analyse = QtWidgets.QWidget(main)
        self.widget_analyse.setObjectName("widget_analyse")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_analyse)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_analyse)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.id = QtWidgets.QLineEdit(self.widget_analyse)
        self.id.setEnabled(True)
        self.id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.id.setPlaceholderText("")
        self.id.setObjectName("id")
        self.horizontalLayout.addWidget(self.id)
        self.line = QtWidgets.QFrame(self.widget_analyse)
        self.line.setEnabled(True)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.widget_analyse)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.amount = QtWidgets.QSpinBox(self.widget_analyse)
        self.amount.setEnabled(True)
        self.amount.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.amount.setMinimum(1)
        self.amount.setMaximum(999)
        self.amount.setObjectName("amount")
        self.horizontalLayout.addWidget(self.amount)
        self.label_4 = QtWidgets.QLabel(self.widget_analyse)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_analyse)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dir = QtWidgets.QLineEdit(self.widget_analyse)
        self.dir.setEnabled(True)
        self.dir.setPlaceholderText("")
        self.dir.setObjectName("dir")
        self.horizontalLayout_2.addWidget(self.dir)
        self.btn_dir = QtWidgets.QToolButton(self.widget_analyse)
        self.btn_dir.setEnabled(True)
        self.btn_dir.setObjectName("btn_dir")
        self.horizontalLayout_2.addWidget(self.btn_dir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_analyse = QtWidgets.QPushButton(self.widget_analyse)
        self.btn_analyse.setEnabled(True)
        self.btn_analyse.setObjectName("btn_analyse")
        self.horizontalLayout_3.addWidget(self.btn_analyse)
        self.btn_table = QtWidgets.QPushButton(self.widget_analyse)
        self.btn_table.setEnabled(True)
        self.btn_table.setObjectName("btn_table")
        self.horizontalLayout_3.addWidget(self.btn_table)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.widget_analyse)
        self.table = QtWidgets.QTableWidget(main)
        self.table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table)
        self.label_6.setBuddy(self.email)
        self.label_5.setBuddy(self.password)
        self.label.setBuddy(self.id)
        self.label_3.setBuddy(self.amount)
        self.label_4.setBuddy(self.amount)
        self.label_2.setBuddy(self.dir)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)
        main.setTabOrder(self.id, self.amount)
        main.setTabOrder(self.amount, self.dir)
        main.setTabOrder(self.dir, self.btn_dir)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Pixiv Agent"))
        self.label_6.setText(_translate("main", "E-mail:"))
        self.label_5.setText(_translate("main", "密码:"))
        self.btn_login.setText(_translate("main", "登录"))
        self.label.setText(_translate("main", "画师ID:"))
        self.label_3.setText(_translate("main", "前"))
        self.label_4.setText(_translate("main", "项"))
        self.label_2.setText(_translate("main", "下载目录:"))
        self.btn_dir.setText(_translate("main", "..."))
        self.btn_analyse.setText(_translate("main", "添加任务"))
        self.btn_table.setText(_translate("main", "下载列表"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("main", "作品ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("main", "作品名称"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("main", "下载进度"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QDialog()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())

