# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PixivAgent.ui'
#
# Created: Sat Feb 14 22:48:09 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.resize(386, 391)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMinimumSize(QtCore.QSize(386, 99))
        main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(main)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_login = QtGui.QWidget(main)
        self.widget_login.setObjectName(_fromUtf8("widget_login"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_login)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.widget_login)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.email = QtGui.QLineEdit(self.widget_login)
        self.email.setObjectName(_fromUtf8("email"))
        self.horizontalLayout_5.addWidget(self.email)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.widget_login)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.password = QtGui.QLineEdit(self.widget_login)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_4.addWidget(self.password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.btn_login = QtGui.QPushButton(self.widget_login)
        self.btn_login.setObjectName(_fromUtf8("btn_login"))
        self.verticalLayout_2.addWidget(self.btn_login)
        self.verticalLayout.addWidget(self.widget_login)
        self.widget_analyse = QtGui.QWidget(main)
        self.widget_analyse.setObjectName(_fromUtf8("widget_analyse"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_analyse)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget_analyse)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.id = QtGui.QLineEdit(self.widget_analyse)
        self.id.setEnabled(True)
        self.id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.id.setPlaceholderText(_fromUtf8(""))
        self.id.setObjectName(_fromUtf8("id"))
        self.horizontalLayout.addWidget(self.id)
        self.line = QtGui.QFrame(self.widget_analyse)
        self.line.setEnabled(True)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.label_3 = QtGui.QLabel(self.widget_analyse)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.amount = QtGui.QSpinBox(self.widget_analyse)
        self.amount.setEnabled(True)
        self.amount.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.amount.setMinimum(1)
        self.amount.setMaximum(999)
        self.amount.setObjectName(_fromUtf8("amount"))
        self.horizontalLayout.addWidget(self.amount)
        self.label_4 = QtGui.QLabel(self.widget_analyse)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget_analyse)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dir = QtGui.QLineEdit(self.widget_analyse)
        self.dir.setEnabled(True)
        self.dir.setPlaceholderText(_fromUtf8(""))
        self.dir.setObjectName(_fromUtf8("dir"))
        self.horizontalLayout_2.addWidget(self.dir)
        self.btn_dir = QtGui.QToolButton(self.widget_analyse)
        self.btn_dir.setEnabled(True)
        self.btn_dir.setObjectName(_fromUtf8("btn_dir"))
        self.horizontalLayout_2.addWidget(self.btn_dir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_analyse = QtGui.QPushButton(self.widget_analyse)
        self.btn_analyse.setEnabled(True)
        self.btn_analyse.setObjectName(_fromUtf8("btn_analyse"))
        self.horizontalLayout_3.addWidget(self.btn_analyse)
        self.btn_table = QtGui.QPushButton(self.widget_analyse)
        self.btn_table.setEnabled(True)
        self.btn_table.setObjectName(_fromUtf8("btn_table"))
        self.horizontalLayout_3.addWidget(self.btn_table)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.widget_analyse)
        self.table = QtGui.QTableWidget(main)
        self.table.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table)
        self.label_6.setBuddy(self.email)
        self.label_5.setBuddy(self.password)
        self.label.setBuddy(self.id)
        self.label_3.setBuddy(self.amount)
        self.label_4.setBuddy(self.amount)
        self.label_2.setBuddy(self.dir)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)
        main.setTabOrder(self.id, self.amount)
        main.setTabOrder(self.amount, self.dir)
        main.setTabOrder(self.dir, self.btn_dir)

    def retranslateUi(self, main):
        main.setWindowTitle(_translate("main", "Pixiv Agent", None))
        self.label_6.setText(_translate("main", "E-mail:", None))
        self.label_5.setText(_translate("main", "密码:", None))
        self.btn_login.setText(_translate("main", "登录", None))
        self.label.setText(_translate("main", "画师ID:", None))
        self.label_3.setText(_translate("main", "前", None))
        self.label_4.setText(_translate("main", "项", None))
        self.label_2.setText(_translate("main", "下载目录:", None))
        self.btn_dir.setText(_translate("main", "...", None))
        self.btn_analyse.setText(_translate("main", "添加任务", None))
        self.btn_table.setText(_translate("main", "下载列表", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("main", "作品ID", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("main", "作品名称", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("main", "下载进度", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    main = QtGui.QDialog()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())

